name: AI SQL Validation

on:
  pull_request:
    types: [opened]   # Trigger only when a PR is created

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      GITHUB_EVENT_PATH: ${{ github.event_path }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests sqlglot

      - name: Run SQL Validation Script
        run: python .github/scripts/sql_validate.py
