name: AI SQL Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install openai PyGithub

      - name: Run SQL Validation Script
        run: python .github/scripts/sql_validate.py
